body_list:
  - torso
  - torso_left_shin
  - torso_right_shin
  - head_left_shin
  - head_right_shin
  - torso_left_thigh
  - torso_right_thigh
  - head_left_thigh
  - head_right_thigh
  - torso_left_front_wheel
  - torso_left_rear_wheel
  - torso_right_front_wheel
  - torso_right_rear_wheel
  - head_left_front_wheel
  - head_left_rear_wheel
  - head_right_front_wheel
  - head_right_rear_wheel

noncontact_site_list:
  - torso_site
  - tl_shin_site
  - tr_shin_site
  - hl_shin_site
  - hr_shin_site
  - tl_thigh_site
  - tr_thigh_site
  - hl_thigh_site
  - hr_thigh_site

contact_site_list:
  - tlf_wheel_site
  - tlr_wheel_site
  - trf_wheel_site
  - trr_wheel_site
  - hlf_wheel_site
  - hlr_wheel_site
  - hrf_wheel_site
  - hrr_wheel_site

friction_coefficient: 0.8

weights_config:
  torso_translational_tracking: 1.0
  torso_rotational_tracking: 10.0

  tls_translational_tracking: 1.0
  tls_rotational_tracking: 1.0
  trs_translational_tracking: 1.0
  trs_rotational_tracking: 1.0
  hls_translational_tracking: 1.0
  hls_rotational_tracking: 1.0
  hrs_translational_tracking: 1.0
  hrs_rotational_tracking: 1.0
  
  # tlh_translational_tracking: 5000.0
  # tlh_rotational_tracking: 100.0
  # trh_translational_tracking: 5000.0
  # trh_rotational_tracking: 100.0
  # hlh_translational_tracking: 5000.0
  # hlh_rotational_tracking: 100.0
  # hrh_translational_tracking: 5000.0
  # hrh_rotational_tracking: 100.0

  tlh_translational_tracking: 500.0
  tlh_rotational_tracking: 1.0
  trh_translational_tracking: 500.0
  trh_rotational_tracking: 1.0
  hlh_translational_tracking: 500.0
  hlh_rotational_tracking: 1.0
  hrh_translational_tracking: 500.0
  hrh_rotational_tracking: 1.0

  tlf_translational_tracking: 10.0
  tlf_rotational_tracking: 10.0
  tlr_translational_tracking: 10.0
  tlr_rotational_tracking: 10.0
  trf_translational_tracking: 10.0
  trf_rotational_tracking: 10.0
  trr_translational_tracking: 10.0
  trr_rotational_tracking: 10.0
  hlf_translational_tracking: 10.0
  hlf_rotational_tracking: 10.0
  hlr_translational_tracking: 10.0
  hlr_rotational_tracking: 10.0
  hrf_translational_tracking: 10.0
  hrf_rotational_tracking: 10.0
  hrr_translational_tracking: 10.0
  hrr_rotational_tracking: 10.0
  torque: 1.0e-4
  regularization: 1.0e-4